import Head from 'next/head'
import { useRef } from 'react'

export default function Home() {
  const emailInputRef = useRef();
  const feedbackInputRef = useRef();

  function submitFormHandler(e){
    e.preventDefault();

    const enteredEmail = emailInputRef.current.value;
    const enteredFeedback = feedbackInputRef.current.value;

  }


  return (
    <>
      <Head>
        <title>API Sample</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>This is homepage</h1>
        <form>
          <div className='form-group'>
            <label htmlFor='email'>Your Email Address</label>
            <input type="email" id="email" placeholder='Enter your email' ref={emailInputRef} />
          </div>
          <div className='form-group'>
            <label htmlFor='feedback'>Your Feedback</label>
            <textarea id="feedback" rows="5" ref={feedbackInputRef}></textarea>
          </div>
          <button>Send Feedback</button>
        </form>
      </main>
    </>
  )
}
